# Category constants
DEEP = "deep"
SHALLOW = "shallow"
ESCAPE = "escape"

SITE_DB: dict[str, str] = {
    # ── DEEP WORK ──────────────────────────────────────────
    "github.com": DEEP,
    "gitlab.com": DEEP,
    "bitbucket.org": DEEP,
    "stackoverflow.com": DEEP,
    "stackexchange.com": DEEP,
    "superuser.com": DEEP,
    "serverfault.com": DEEP,
    "docs.python.org": DEEP,
    "developer.mozilla.org": DEEP,
    "mdn.io": DEEP,
    "reactjs.org": DEEP,
    "react.dev": DEEP,
    "vuejs.org": DEEP,
    "angular.io": DEEP,
    "nextjs.org": DEEP,
    "vercel.com": DEEP,
    "netlify.com": DEEP,
    "railway.app": DEEP,
    "render.com": DEEP,
    "fly.io": DEEP,
    "aws.amazon.com": DEEP,
    "console.aws.amazon.com": DEEP,
    "cloud.google.com": DEEP,
    "console.cloud.google.com": DEEP,
    "portal.azure.com": DEEP,
    "azure.microsoft.com": DEEP,
    "figma.com": DEEP,
    "sketch.com": DEEP,
    "framer.com": DEEP,
    "linear.app": DEEP,
    "notion.so": DEEP,
    "notions.com": DEEP,
    "obsidian.md": DEEP,
    "roamresearch.com": DEEP,
    "logseq.com": DEEP,
    "docs.google.com": DEEP,
    "drive.google.com": DEEP,
    "sheets.google.com": DEEP,
    "slides.google.com": DEEP,
    "airtable.com": DEEP,
    "coda.io": DEEP,
    "clickup.com": DEEP,
    "asana.com": DEEP,
    "jira.atlassian.com": DEEP,
    "confluence.atlassian.com": DEEP,
    "atlassian.com": DEEP,
    "trello.com": DEEP,
    "basecamp.com": DEEP,
    "monday.com": DEEP,
    "height.app": DEEP,
    "shortcut.com": DEEP,
    "cursor.sh": DEEP,
    "replit.com": DEEP,
    "codesandbox.io": DEEP,
    "codepen.io": DEEP,
    "jsfiddle.net": DEEP,
    "kaggle.com": DEEP,
    "colab.research.google.com": DEEP,
    "jupyter.org": DEEP,
    "huggingface.co": DEEP,
    "arxiv.org": DEEP,
    "paperswithcode.com": DEEP,
    "semanticscholar.org": DEEP,
    "pubmed.ncbi.nlm.nih.gov": DEEP,
    "scholar.google.com": DEEP,
    "researchgate.net": DEEP,
    "jstor.org": DEEP,
    "coursera.org": DEEP,
    "udemy.com": DEEP,
    "edx.org": DEEP,
    "khanacademy.org": DEEP,
    "pluralsight.com": DEEP,
    "egghead.io": DEEP,
    "frontendmasters.com": DEEP,
    "leetcode.com": DEEP,
    "hackerrank.com": DEEP,
    "codewars.com": DEEP,
    "exercism.org": DEEP,
    "adventofcode.com": DEEP,
    "pypi.org": DEEP,
    "npmjs.com": DEEP,
    "crates.io": DEEP,
    "rubygems.org": DEEP,
    "pkg.go.dev": DEEP,
    "readthedocs.io": DEEP,
    "readthedocs.org": DEEP,
    "gitbook.io": DEEP,
    "postman.com": DEEP,
    "insomnia.rest": DEEP,
    "swagger.io": DEEP,
    "dbdiagram.io": DEEP,
    "drawio.com": DEEP,
    "lucidchart.com": DEEP,
    "mermaid.live": DEEP,
    "supabase.com": DEEP,
    "planetscale.com": DEEP,
    "neon.tech": DEEP,
    "mongodb.com": DEEP,
    "redis.io": DEEP,
    "postgresql.org": DEEP,
    "mysql.com": DEEP,
    "quicksight.aws.amazon.com": DEEP,
    "lookerstudio.google.com": DEEP,
    "tableau.com": DEEP,
    "powerbi.microsoft.com": DEEP,
    "metabase.com": DEEP,
    "grafana.com": DEEP,
    "datadog.com": DEEP,
    "sentry.io": DEEP,
    "anthropic.com": DEEP,
    "openai.com": DEEP,
    "perplexity.ai": DEEP,
    "claude.ai": DEEP,
    # ── SHALLOW ────────────────────────────────────────────
    "gmail.com": SHALLOW,
    "mail.google.com": SHALLOW,
    "outlook.com": SHALLOW,
    "outlook.live.com": SHALLOW,
    "mail.yahoo.com": SHALLOW,
    "protonmail.com": SHALLOW,
    "hey.com": SHALLOW,
    "fastmail.com": SHALLOW,
    "slack.com": SHALLOW,
    "app.slack.com": SHALLOW,
    "teams.microsoft.com": SHALLOW,
    "discord.com": SHALLOW,
    "zoom.us": SHALLOW,
    "meet.google.com": SHALLOW,
    "calendar.google.com": SHALLOW,
    "calendar.apple.com": SHALLOW,
    "calendly.com": SHALLOW,
    "cal.com": SHALLOW,
    "loom.com": SHALLOW,
    "dropbox.com": SHALLOW,
    "box.com": SHALLOW,
    "onedrive.live.com": SHALLOW,
    "wetransfer.com": SHALLOW,
    "whatsapp.com": SHALLOW,
    "web.whatsapp.com": SHALLOW,
    "telegram.org": SHALLOW,
    "web.telegram.org": SHALLOW,
    "messenger.com": SHALLOW,
    "amazon.com": SHALLOW,
    "ebay.com": SHALLOW,
    "etsy.com": SHALLOW,
    "producthunt.com": SHALLOW,
    "ycombinator.com": SHALLOW,
    "news.ycombinator.com": SHALLOW,
    "techcrunch.com": SHALLOW,
    "venturebeat.com": SHALLOW,
    "theverge.com": SHALLOW,
    "arstechnica.com": SHALLOW,
    "wired.com": SHALLOW,
    "medium.com": SHALLOW,
    "substack.com": SHALLOW,
    "dev.to": SHALLOW,
    "hashnode.com": SHALLOW,
    "wikipedia.org": SHALLOW,
    "en.wikipedia.org": SHALLOW,
    "maps.google.com": SHALLOW,
    "google.com": SHALLOW,
    "bing.com": SHALLOW,
    "duckduckgo.com": SHALLOW,
    "apple.com": SHALLOW,
    "support.apple.com": SHALLOW,
    "linkedin.com": SHALLOW,
    "www.linkedin.com": SHALLOW,
    # ── ESCAPE ─────────────────────────────────────────────
    "youtube.com": ESCAPE,
    "www.youtube.com": ESCAPE,
    "youtu.be": ESCAPE,
    "twitter.com": ESCAPE,
    "x.com": ESCAPE,
    "reddit.com": ESCAPE,
    "old.reddit.com": ESCAPE,
    "instagram.com": ESCAPE,
    "www.instagram.com": ESCAPE,
    "facebook.com": ESCAPE,
    "www.facebook.com": ESCAPE,
    "tiktok.com": ESCAPE,
    "www.tiktok.com": ESCAPE,
    "snapchat.com": ESCAPE,
    "pinterest.com": ESCAPE,
    "tumblr.com": ESCAPE,
    "twitch.tv": ESCAPE,
    "www.twitch.tv": ESCAPE,
    "netflix.com": ESCAPE,
    "www.netflix.com": ESCAPE,
    "hulu.com": ESCAPE,
    "disneyplus.com": ESCAPE,
    "primevideo.com": ESCAPE,
    "hbomax.com": ESCAPE,
    "max.com": ESCAPE,
    "peacocktv.com": ESCAPE,
    "crunchyroll.com": ESCAPE,
    "9gag.com": ESCAPE,
    "buzzfeed.com": ESCAPE,
    "dailymail.co.uk": ESCAPE,
    "tmz.com": ESCAPE,
    "espn.com": ESCAPE,
    "nfl.com": ESCAPE,
    "nba.com": ESCAPE,
    "mlb.com": ESCAPE,
    "sports.yahoo.com": ESCAPE,
    "bleacherreport.com": ESCAPE,
    "steamcommunity.com": ESCAPE,
    "store.steampowered.com": ESCAPE,
    "epicgames.com": ESCAPE,
    "chess.com": ESCAPE,
    "lichess.org": ESCAPE,
    "miniclip.com": ESCAPE,
    "wordlewebsite.com": ESCAPE,
    "nytimes.com/games": ESCAPE,
    "spotify.com": ESCAPE,
    "open.spotify.com": ESCAPE,
    "soundcloud.com": ESCAPE,
    "news.google.com": ESCAPE,
    "yahoo.com": ESCAPE,
    "msn.com": ESCAPE,
    "huffpost.com": ESCAPE,
    "buzzfeednews.com": ESCAPE,
}


DEEP_KEYWORDS = [
    "github", "gitlab", "docs", "dev", "api", "code",
    "stackoverflow", "documentation", "learn", "course",
    "tutorial", "engineer", "deploy", "cloud", "database",
]

ESCAPE_KEYWORDS = [
    "game", "games", "play", "stream", "watch", "video",
    "meme", "funny", "entertainment", "celebrity", "gossip",
    "porn", "xxx", "bet", "casino", "lottery",
]

SHALLOW_KEYWORDS = [
    "mail", "email", "calendar", "meeting", "news",
    "shop", "store", "buy", "chat", "message",
]


def lookup(domain: str) -> str:
    """Return category for a domain. Falls back to keyword matching."""
    domain = domain.lower().replace("www.", "")
    if domain in SITE_DB:
        return SITE_DB[domain]
    for kw in ESCAPE_KEYWORDS:
        if kw in domain:
            return ESCAPE
    for kw in DEEP_KEYWORDS:
        if kw in domain:
            return DEEP
    for kw in SHALLOW_KEYWORDS:
        if kw in domain:
            return SHALLOW
    return SHALLOW  # default unknown to shallow